import { ActionTree } from 'vuex';
import { LeadState, Lead } from './types';
import { RootState } from '..';

export const actions: ActionTree<LeadState, RootState> = {
    setLead({commit}, lead: Lead) {
        commit('setLead', lead);
    },
    setLeadDefault({commit}) {
        commit('setLead', {        
            id: '',
            firstName: '',
            lastName: '',
            leadType: '',
            registeredDate: '',
            phoneNumber: '',
            email: ''});
    },
    getLeads({commit}) {
        const mockLeads: Lead[] = [
            {
                id: 'abc',
                firstName: 'Test',
                lastName: 'One',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(1)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: 'def',
                firstName: 'Test',
                lastName: 'Two',
                leadType: 'Seller',
                registeredDate: new Date(new Date().setDate(13)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: 'ghi',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: 'jkl',
                firstName: 'Test',
                lastName: 'One',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(1)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: 'mno',
                firstName: 'Test',
                lastName: 'Two',
                leadType: 'Seller',
                registeredDate: new Date(new Date().setDate(13)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: 'pqr',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },            
            {
                id: 'stu',
                firstName: 'Test',
                lastName: 'One',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(1)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: 'vwx',
                firstName: 'Test',
                lastName: 'Two',
                leadType: 'Seller',
                registeredDate: new Date(new Date().setDate(13)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: 'yz0',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '123',
                firstName: 'Test',
                lastName: 'One',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(1)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '456',
                firstName: 'Test',
                lastName: 'Two',
                leadType: 'Seller',
                registeredDate: new Date(new Date().setDate(13)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '7891',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '781',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '782',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '783',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '784',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '785',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '786',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '787',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '788',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '789',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '790',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '791',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },
            {
                id: '792',
                firstName: 'Test',
                lastName: 'Three',
                leadType: 'Buyer',
                registeredDate: new Date(new Date().setDate(27)).toDateString(),
                phoneNumber: '123-456-7891',
                email: 'my.email@gmail.com',
            },        
        ];
        commit('setLeads', mockLeads);
    },
};
